% Please type bcilab in the command window before running the code
% Define class markers: class 1 = T1 (left hand), class 2 = T2 (right hand)
targetmarkers = {'T1','T2'};
% Define ERP time windows (post-stimulus)
% Total epoch was from -1 to 4 s, but we only used [0–2.5] in 5 intervals
wnds = [0 0.5; 0.5 1; 1 1.5; 1.5 2; 2 2.5];
% Load training data (EEGLAB .set file)
traindata = io_loadset('C:\Germany 2024\BTU\Sem 2\BCI\report\S008_L_vs_R_hand.set');
% Define the classification approach
myapproach = {'Windowmeans', ...
'SignalProcessing', { ...
'EpochExtraction', [-1 4], ...
'SpectralSelection', [8 30] ...
}, ...
'Prediction', { ...
'FeatureExtraction', {'TimeWindows', wnds}, ...
'MachineLearning', {'Learner', 'lda'} ...
}};
% Train model
[trainloss, model, stats] = bci_train('Data', traindata, ...
'Approach', myapproach, ...
'TargetMarkers', targetmarkers);
fprintf('Training misclassification rate: %.2f%%\n', trainloss * 100);
% Visualize
bci_visualize(model);
%Display confusion matrix
gui_reviewresults(stats);